# This file was generated by GoReleaser. DO NOT EDIT.
cask "iac-coolify" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "30b5cc5bd9fdf6983573822ced6bef4e10715a6d055af78f8d3bb3a5f2a7afdf"
      url "https://github.com/Rems08/infrastructure-as-coolify/releases/download/v#{version}/iac-coolify_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "100089b0baf2e51da1242131719ca6764d22850efb42acd8d9cf5d0fe3e6607b"
      url "https://github.com/Rems08/infrastructure-as-coolify/releases/download/v#{version}/iac-coolify_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "53e261f8be3a3fd1992e36a2c5e7e7874f1bf89f6513bda742895020ace8de46"
      url "https://github.com/Rems08/infrastructure-as-coolify/releases/download/v#{version}/iac-coolify_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3282a2dab42a57fb71c978c8a22941515410dbbd0182d50754752c4745fd4ff9"
      url "https://github.com/Rems08/infrastructure-as-coolify/releases/download/v#{version}/iac-coolify_#{version}_linux_arm64.tar.gz"
    end
  end

  name "iac-coolify"
  desc "Declarative Infrastructure as Code for Coolify"
  homepage "https://github.com/Rems08/infrastructure-as-coolify"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iac-coolify"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/iac-coolify"]
    end
  end

  # No zap stanza required

end
