# This file was generated by GoReleaser. DO NOT EDIT.
cask "iac-coolify" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "0adabb006ef0c3c46dd7c287351c67e4306dd71a0efd52dd7b72dbd348437cf1"
      url "https://github.com/Rems08/infrastructure-as-coolify/releases/download/v#{version}/iac-coolify_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5206d587c789d451e29a04d8c236ff44d34412ae48237d693158565c0c6c5358"
      url "https://github.com/Rems08/infrastructure-as-coolify/releases/download/v#{version}/iac-coolify_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "52f8234bb8c258c0304486b0d02a0aea0f0b039457eda34c71e77537c7d2f994"
      url "https://github.com/Rems08/infrastructure-as-coolify/releases/download/v#{version}/iac-coolify_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "530340f96abc796fcc7c001f34c133b599cd4822fa407bfebd02d539445dcdba"
      url "https://github.com/Rems08/infrastructure-as-coolify/releases/download/v#{version}/iac-coolify_#{version}_linux_arm64.tar.gz"
    end
  end

  name "iac-coolify"
  desc "Declarative Infrastructure as Code for Coolify"
  homepage "https://github.com/Rems08/infrastructure-as-coolify"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iac-coolify"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/iac-coolify"]
    end
  end

  # No zap stanza required

end
