package docs

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Rems08/infrastructure-as-coolify/internal/resource"
)

// Generate writes docs/reference/application.md and docs/reference/schema.json derived
// from the resource structs in resourceDir, into outDir.
func Generate(resourceDir, outDir string) error {
	structs, err := ExtractStructDocs(resourceDir)
	if err != nil {
		return err
	}
	if err = os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", outDir, err)
	}

	md := RenderMarkdown(structs)
	if err = os.WriteFile(filepath.Join(outDir, "application.md"), []byte(md), 0o600); err != nil {
		return fmt.Errorf("write application.md: %w", err)
	}

	schemaJSON, err := json.MarshalIndent(resource.ApplicationSchema(), "", "  ")
	if err != nil {
		return fmt.Errorf("marshal schema: %w", err)
	}
	schemaJSON = append(schemaJSON, '\n')
	if err = os.WriteFile(filepath.Join(outDir, "schema.json"), schemaJSON, 0o600); err != nil {
		return fmt.Errorf("write schema.json: %w", err)
	}
	return nil
}

// RenderMarkdown produces the Diátaxis-style reference for the Application resource.
func RenderMarkdown(structs []StructDoc) string {
	var b strings.Builder
	b.WriteString("# Application\n\n")
	b.WriteString("> Generated by `iac-coolify docs gen` from the struct tags in ")
	b.WriteString("`internal/resource`. Do not edit by hand.\n\n")
	b.WriteString("This is the reference for the `Application` resource and its nested types. ")
	b.WriteString("Each field below maps 1:1 to a YAML key.\n\n")

	for _, s := range structs {
		fmt.Fprintf(&b, "## %s\n\n", s.Name)
		for _, f := range s.Fields {
			renderField(&b, f)
		}
	}
	return b.String()
}

func renderField(b *strings.Builder, f FieldDoc) {
	fmt.Fprintf(b, "### %s\n\n", f.YAMLName)
	b.WriteString(f.Doc)
	b.WriteString(".\n\n")
	if f.Required {
		b.WriteString("- **Required.**\n")
	}
	if len(f.Enum) > 0 {
		fmt.Fprintf(b, "- Allowed values: `%s`.\n", strings.Join(f.Enum, "`, `"))
	}
	b.WriteString("\n")
}
