package docs

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Rems08/infrastructure-as-coolify/internal/resource"
)

// Generate writes one docs/reference/<slug>.md and one <slug>.schema.json per resource
// declared in resourceDir, into outDir.
func Generate(resourceDir, outDir string) error {
	resources, err := ExtractResourceDocs(resourceDir)
	if err != nil {
		return err
	}
	if err = os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", outDir, err)
	}
	schemas := resource.Schemas()
	for _, rd := range resources {
		md := RenderResource(rd)
		if err = os.WriteFile(filepath.Join(outDir, rd.Slug+".md"), []byte(md), 0o600); err != nil {
			return fmt.Errorf("write %s.md: %w", rd.Slug, err)
		}
		schema, ok := schemas[rd.Slug]
		if !ok {
			continue
		}
		schemaJSON, mErr := json.MarshalIndent(schema, "", "  ")
		if mErr != nil {
			return fmt.Errorf("marshal %s schema: %w", rd.Slug, mErr)
		}
		schemaJSON = append(schemaJSON, '\n')
		if err = os.WriteFile(filepath.Join(outDir, rd.Slug+".schema.json"), schemaJSON, 0o600); err != nil {
			return fmt.Errorf("write %s.schema.json: %w", rd.Slug, err)
		}
	}
	return nil
}

// RenderResource produces the Diátaxis-style reference for one resource and its nested
// types. Each field maps 1:1 to a YAML key.
func RenderResource(rd ResourceDoc) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", rd.Title)
	b.WriteString("> Generated by `iac-coolify docs gen` from the struct tags in ")
	b.WriteString("`internal/resource`. Do not edit by hand.\n\n")
	fmt.Fprintf(&b, "This is the reference for the `%s` resource and its nested types. ", rd.Title)
	b.WriteString("Each field below maps 1:1 to a YAML key.\n\n")

	for _, s := range rd.Structs {
		fmt.Fprintf(&b, "## %s\n\n", s.Name)
		for _, f := range s.Fields {
			renderField(&b, f)
		}
	}
	return b.String()
}

func renderField(b *strings.Builder, f FieldDoc) {
	fmt.Fprintf(b, "### %s\n\n", f.YAMLName)
	b.WriteString(f.Doc)
	b.WriteString(".\n\n")
	if f.Required {
		b.WriteString("- **Required.**\n")
	}
	if len(f.Enum) > 0 {
		fmt.Fprintf(b, "- Allowed values: `%s`.\n", strings.Join(f.Enum, "`, `"))
	}
	b.WriteString("\n")
}
